//Try : "the try statement allows you to define a block for errors while it is being executed.
//Catch : "the catch statement allows you to define a block of code to be executed if an error occurs in try block".


/* without try and catch

console.log("Hello");
console.log(a);
console.log("a");


In the above code we'll only get hello as output and then an error that a is not defined
*/

/* With Try and Catch

console.log("Hello");
try{
console.log(A)
}
catch{
console.log("A")
}

In this we'll get the output as hello and A as the code in try block will catch the error and will keep the code running.
*/

